export const TotalStack: string[] = [
  "react",
  "react router",
  "react hook form",
  "styled components",
  "react query",
  "node.js",
  "express",
  "mongoDB",
  "cloudinary",
  "heroku",
  "git workflow",
  "storybook",
  "javascript",
  "html",
  "css",
  "bootstrap",
  "webpack",
  "json",
  " restful api",
];
export const CraftifiedStack: string[] = [
  "react",
  "react router",
  "react hook form",
  "styled components",
  "react query",
  "node.js",
  "express",
  "mongoDB",
  "cloudinary",
  "heroku",
  "git workflow",
  "storybook",
];
